//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chamuscopolis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cancha()
        {
            this.horarios = new HashSet<horario>();
            this.reservacions = new HashSet<reservacion>();
        }
    
        public int idCANCHA { get; set; }
        public string Ttpo { get; set; }
        public string nombre { get; set; }
        public sbyte disponibilidad { get; set; }
        public int SEDE_idSEDE { get; set; }
        public sbyte estatus { get; set; }
        public decimal precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario> horarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservacion> reservacions { get; set; }
        public virtual sede sede { get; set; }
    }
}
