//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chamuscopolis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prosgEntities : DbContext
    {
        public prosgEntities()
            : base("name=prosgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cancha> canchas { get; set; }
        public virtual DbSet<hora> horas { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<reservacion> reservacions { get; set; }
        public virtual DbSet<sede> sedes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
